# Generated by Django 4.2.4 on 2023-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='note',
            field=models.TextField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
